[project]
name = "tech-interview-prep"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Oleg Bordun", email = "oleg.bordun@outlook.com" }
]
requires-python = ">=3.14"
dependencies = []

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
